# Generated by Django 3.0.6 on 2020-05-13 16:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bms_admin',
            fields=[
                ('gh', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('ISBN', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=80, null=True)),
                ('author', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('ID', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=80, null=True)),
                ('status', models.CharField(choices=[('预约', '预约'), ('借出', '借出'), ('架上', '架上')], default='架上', max_length=80)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.booklist')),
            ],
        ),
        migrations.CreateModel(
            name='readers',
            fields=[
                ('readerId', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('balance', models.DecimalField(decimal_places=3, default=100.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserveTime', models.DateField()),
                ('reserveLength', models.DecimalField(decimal_places=0, default=5, max_digits=3)),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.books')),
                ('readerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.readers')),
            ],
        ),
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowTime', models.DateField()),
                ('status', models.CharField(choices=[('未归还', '未归还'), ('已归还', '已归还')], max_length=80)),
                ('returnTime', models.DateField()),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.books')),
                ('readerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMS.readers')),
            ],
        ),
    ]
