# Generated by Django 3.0.6 on 2020-05-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
