# Generated by Django 3.0.6 on 2020-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0003_auto_20200521_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_admin',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
