# Generated by Django 3.0.7 on 2020-06-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0004_auto_20200521_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='position',
            field=models.CharField(choices=[('阅览室', '阅览室'), ('图书室', '图书室')], max_length=80, null=True),
        ),
    ]
