# Generated by Django 3.0.7 on 2020-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0005_auto_20200619_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
