# Generated by Django 3.0.7 on 2020-06-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMS', '0006_booklist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='pub_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='publisher',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
